Database:
  # type: sqlite, MySQL
  type: sqlite
  MySQL:
    host: localhost
    port: 3306
    database: database
    user: user
    password: password
  SyncWrite: false #資料更新時是否同步寫入資料庫
  AutosaveInterval: 12000 #自動保存間隔 單位tick
  debug: false
Features:
  AbsorptionScale:
    enable: true
    debug: false
    max_amount: 20 #吸收生命縮放值
  DamageIndicatorLimiter:
    enable: true
    debug: false
    max_amount: 20 #受擊粒子最大數量
  ShulkerBox:
    enable: true
    debug: false
    cooldown: 1000 #冷卻時間 單位毫秒
  Elevator:
    enable: true
    debug: false
    elevators:
      - 'QUARTZ_BLOCK, REDSTONE_BLOCK'
      - 'LIGHT_GRAY_CARPET, WHITE_WOOL'
    max_distance: 64
  LightBlock:
    enable: true
    debug: false
  ArmorHide:
    enable: true
    debug: false
  VirtualWorkbench:
    enable: true
    debug: false
  PlaceholderAPI:
    enable: true
    debug: false