Database:
  # type: sqlite, MySQL
  type: sqlite
  MySQL:
    host: localhost
    port: 3306
    database: database
    user: user
    password: password
Features:
  AbsorptionScale:
    enable: true
    max_amount: 20
  DamageIndicatorLimiter:
    enable: true
    max_amount: 20
  ShulkerBox:
    enable: true
    cooldown: 1000
  Elevator:
    enable: true
    elevators:
      - 'QUARTZ_BLOCK, REDSTONE_BLOCK'
      - 'LIGHT_GRAY_CARPET, WHITE_WOOL'
    max_distance: 64
  LightBlock:
    enable: true
  ArmorHide:
    enable: true